export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ 
          backgroundColor: 'lightblue',
          padding: '1rem',
        }}>
          <h1>Next.js</h1>
        </header>
        {children}
        <footer style={{ 
          backgroundColor: 'lightgray',
          padding: '1rem',
        }}>
          <h1>Footer</h1>
        </footer>
      </body>
    </html>
  );
};
